<a class="button" href="<?php echo $this->link(null,'edit',null) ?>">Créer event</a>
<div class="clear"></div>

<?php echo $this->displayMessages($this->messages); ?>

<?php 
$th = array(
    array('lib' => '', 'style'=>'width:45px;'),         // ex : array('lib'=>'', 'class'=>'foo bar', 'style'=>'foo:bar;'),
    array('lib' => 'Id'),
    array('lib' => 'Nom'),
    array('lib' => 'Date heure'),
    array('lib' => 'Description'),
    array('lib' => 'Url'),
    array('lib' => 'Date insert'),
    array('lib' => 'Actif'),
    array('lib' => 'Prix'),
);

$tr = array();
foreach ($this->rows as $row) {
    $link = $this->link(null,'edit',null,array('uid'=>$row->getId()));
    $tr[] = array(
        'attrib' => array(),    // ex : array('class'=>'foo', 'style'=>'bar')
        'link' => $link,        // enlever si ligne non cliquable
        'cols' => array(
            '<a href="' . $this->link(null,'suppr',null,array('uid'=>$row->getId())) . '"><img src="' . $this->baseUrl('/images/icons/delete.png') . '" alt="Supprimer" title="Supprimer" /></a>'
           .' <a href="' . $this->link(null,'edit',null,array('uid'=>$row->getId())) . '"><img src="' . $this->baseUrl('/images/icons/edit.png') . '" alt="Edit" title="Editer" /></a>',
            $row->getId(),
            $row->getNom(),
            $row->getDate_heure(),
            $row->getDescription(),
            $row->getUrl(),
            $row->getDate_insert(),
            $row->getActif(),
            $row->getPrix(),
        )
    );
}
$large = false;     // width:100% si true
echo $this->DisplayList($th, $tr, $large); 

?>