<?php 
$model = new Model_Users();
$model->info($this->uid);
?>

<a class="button" href="<?php echo $this->link(null,'index') ?>">Retour à la liste</a>
<a class="button" href="<?php echo $this->link(null,'edit',null,array('uid'=>$this->uid))?>">Modifier les informations</a>
<div class="clear"></div>

<?php 
$title = 'Users';

$rows = array();
$rows[] = array('Id' => $model->getId());
$rows[] = array('Nom' => $model->getNom());
$rows[] = array('Prenom' => $model->getPrenom());
$rows[] = array('Login' => $model->getLogin());
$rows[] = array('Pass' => $model->getPass());
$rows[] = array('Email' => $model->getEmail());
$rows[] = array('Actif' => $model->getActif());
$rows[] = array('Last connect' => $model->getLast_connect());


echo $this->displayInfo($rows, $title);
?>